contact_links:
  - name: ❔ Github Community Support
    url: https://github.com/ipincamp/whatsapp-client/discussions
    about: Please ask and answer questions here.
  - name: ⚔️ Discord Community Server
    url: https://discord.gg/FGw4nCbfqB
    about: Let's talk about future features.
